#!/bin/bash

if [ "$1" = "--help" ] || [ "$1" = "-h" ] ; then
  exit
fi

mkdir -p $1images $1sounds $1documents $1movies


mv *.jpg *.png *.img $1images 2>/dev/null
mv *.mp4 $1movies 2>/dev/null
mv *.pdf *.html $1documents 2>/dev/null
mv *.mp3 $1sounds 2>/dev/null


for folder in *
do

 rmdir $folder 2>/dev/null

done


exit
